kind: ConfigMap
apiVersion: v1
metadata:
  name: pihole-config
  labels:
    app: pihole-test
data:
  dns:
    upstreams:
    - 94.140.14.14
    - 94.140.15.15
    - 2a10:50c0::ad1:ff
    - 2a10:50c0::ad2:ff
    - 1.1.1.1
    - 1.0.0.1
    - 2606:4700:4700::1111
    - 2606:4700:4700::1001
    dnssec: true
    listeningMode: ALL
  webserver:
    domain: dns.dekiru.tech
