apiVersion: v1
kind: Service
metadata:
  name: pihole-test-web
  labels:
    app: pihole-test
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: pihole-test

---

apiVersion: v1
kind: Service
metadata:
  name: pihole-test-dns-udp
  labels:
    app: pihole-test
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  ports:
  - port: 53543
    targetPort: dns-tcp
    protocol: TCP
    name: dns-tcp
  selector:
    app: pihole-test

---

apiVersion: v1
kind: Service
metadata:
  name: pihole-test-dns-tcp
  labels:
    app: pihole-test
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  ports:
  - port: 53543
    targetPort: dns-tcp
    protocol: TCP
    name: dns-tcp
  selector:
    app: pihole-test
