kind: ConfigMap
apiVersion: v1
metadata:
  name: unbound
  labels:
    app: unbound
    role: config
data:
  server.conf: |
    server:
        logfile: ""
        log-queries: yes
        verbosity: 3

        interface: 0.0.0.0
        interface: ::0
        port: 5335

        do-ip6: yes

        access-control: 0.0.0.0/0 allow
        access-control: ::0/0 allow
        ip-transparent: yes

        local-data: "photos.erdos.tech. 10800 IN A 1.2.3.4"
  local.conf: |
    server:
        access-control-view: 192.168.0.0/24 home-local
    view:
        name: "home-local"
        local-data: "photos.erdos.tech. 10800 IN A 192.168.0.240"
  tailscale.conf: |
    server:
        access-control-view: 100.0.0.0/8 tailscale
    view:
        name: "tailscale"
        local-data: "photos.erdos.tech. 10800 IN A 100.92.110.126"
        local-data: "photos.erdos.tech. 10800 IN AAAA fd7a:115c:a1e0::5f01:6e81"
